### ISSUE TITLE
Can't connect to Hangouts anymore

### ISSUE THREAD

**Issue by hastebrot** [yakyak/hangupsjs#60]
Since today (December 1st 2016, GMT) my client can't connect to Hangouts anymore. It remains in a reconnect loop.

I requested/renewed my OAUTH2 credentials using the approach described in https://github.com/tdryer/hangups/issues/260#issuecomment-247512300. But it doesn't work.

The `hangups` command (Python-version) works however.

Versions:

- `hangupsjs` 1.3.2
- `hangups` 0.4.1

**Comment by quazzie** [comment]
temp fix:
edit lib/init.js
line 124 change to :
_this[k] = d = (spec.fn(ent.data()) || []);
Can't list conversations any more but if you don't use it no prob.

**Comment by averissimo** [comment]
@hastebrot  @quazzie there's a beta version available that corrects this.

https://github.com/yakyak/yakyak/releases/v1.4.0-beta4

please try 1.4.0-beta4 in the releases (I'm updating as it was not well packaged, but all the platforms should be available in the next half an hour)

Currently only has the macOSX package

**Comment by averissimo** [comment]
@hastebrot @quazzie sorry guys I didn't notice that this was not yakyak

I've corrected this in averissimo/hangupsjs see f50a52e5159a85caa5f87d41981d008a4693c716

hangups version changed the way the deal with the server initial. I believe that instead of relying on the initial data from the connection (as hangupsjs does)

it simply uses functions that retrieve that information separately (better approach in my opinion, but I really don't know enough of this library to have a cool overview)

**Comment by hastebrot** [comment]
@averissimo It works. Thanks!

**Comment by hastebrot** [comment]
@quazzie Is there an internal error message that gives some insights about this? At least it would be nice to find a way to prevent the client to reconnect, when there is a serious error.
